language: python

install:
  - pip install -r requirements.txt
  - pip install black
  - pip install flake8
  - pip install coverage

before_script:
  - python manage.py migrate
  - python manage.py collectstatic --noinput

script:
  - python manage.py
  - black --check .
  - flake8 --max-line-length=92
  - coverage run --source='.' manage.py test

after_success:
  - coveralls